### ISSUE TITLE
Download link for Spark no longer Valid

### ISSUE THREAD

**Issue by arjun289** [michaelchanwahyan/datalab#26]
![Screenshot from 2022-05-22 22-54-09](https://user-images.githubusercontent.com/9413385/169707664-5ca0e603-cd4a-4854-83b3-01310ceccdb1.png)

The link to install spark is no longer valid as a result the image building step is fails.

**Comment by michaelchanwahyan** [comment]
hi @arjun289 , thx for pointing out the issue.
it seems that Apache has moved the package of version 3.2.0 to "Older non-recommended releases" and is thus allocated to their archive site

a hot fix would be to use the link https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz instead

I shall evaluate and see whether a newer set of version config shall be adopted in the project.

Thx ~

**Comment by michaelchanwahyan** [comment]
currently fixed in commit [f9ad4ca](https://github.com/michaelchanwahyan/datalab/commit/f9ad4ca44a0b6e67cc2ee736050a19fcefe575e9)

**Comment by arjun289** [comment]
Is there a plan to move it to a stable release such as 3.2.1

**Comment by michaelchanwahyan** [comment]
hi @arjun289 ,

the promotion of SPARK to 3.2.1 is completed in [a07c186](https://github.com/michaelchanwahyan/datalab/commit/a07c186f9f28ac63c46b1e06c96b01f4502835b3).
thanks for your kind attention and support ~

bests,
michael

**Comment by arjun289** [comment]
Thank you @michaelchanwahyan 👍
