### ISSUE TITLE
jdk-8u171-linux-x64.tar.gz file cannot be cloned correctly

### ISSUE THREAD

**Issue by IcarusSO** [michaelchanwahyan/datalab#4]
The jdk file always cannot be downloaded by git clone, although it can be copied by
wget https://github.com/michaelchanwahyan/datalab/raw/master/jdk-8u171-linux-x64.tar.gz

**Comment by michaelchanwahyan** [comment]
git-lfs is required in manipulating large files in git, say the jdk zip file of size few hundred MB.

**Comment by IcarusSO** [comment]
Page of installation is updated, thanks

**Comment by michaelchanwahyan** [comment]
thanks for your update~
