### ISSUE TITLE
master branch build failure due to airflow

### ISSUE THREAD

**Issue by michaelchanwahyan** [michaelchanwahyan/datalab#6]
the following error
"No matching distribution found for airflow==1.8.0"
is received during python package installation.

**Comment by IcarusSO** [comment]
Seems the python package is renamed as apache-airflow.
https://pypi.org/project/airflow/
pip install airflow is deprecated

**Comment by michaelchanwahyan** [comment]
to fix the current issue,
the following changes (or any equivalent alternatives) are required
`export AIRFLOW_GPL_UNIDECODE=yes`
`pip3 install apache-airflow==1.10.1`

they will be brought to master branch soon
